### ISSUE TITLE
what does the reference with sql server have to do with this article?

### ISSUE THREAD

**Issue by baleng** [MicrosoftDocs/azure-docs.it-it#198]
https://docs.microsoft.com/it-it/azure/virtual-machines/workloads/oracle/oracle-design#disk-cache-settings

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 9d2baad7-03e3-a26c-f831-900ab3e3ae38
* Version Independent ID: d5f1631a-39ca-bcd7-eade-c90b608d3e70
* Content: [Progettare e implementare un database Oracle in Azure](https://docs.microsoft.com/it-it/azure/virtual-machines/workloads/oracle/oracle-design)
* Content Source: [articles/virtual-machines/workloads/oracle/oracle-design.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/virtual-machines/workloads/oracle/oracle-design.md)
* Service: **virtual-machines-linux**
* GitHub Login: @romitgirdhar
* Microsoft Alias: **rogirdh**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #24707](https://github.com/MicrosoftDocs/azure-docs/issues/24707) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @baleng 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
