### ISSUE TITLE
This documentation needs an update

### ISSUE THREAD

**Issue by Dan-cws** [MicrosoftDocs/azure-docs.it-it#199]
The example iothub_client_sample_mqtt no longer exists. According to this https://github.com/Azure/azure-iot-sdk-c/issues/406 was substituted by iothub_ll_telemetry_sample. 
Please update this page.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: e6c3553f-2073-38e0-4a93-7aaf483ce66c
* Version Independent ID: 8354a3d4-2117-5948-a6eb-72a09d48eed7
* Content: [Azure IoT SDK per dispositivi per C](https://docs.microsoft.com/it-it/azure/iot-hub/iot-hub-device-sdk-c-intro)
* Content Source: [articles/iot-hub/iot-hub-device-sdk-c-intro.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/live/articles/iot-hub/iot-hub-device-sdk-c-intro.md)
* Service: **iot-hub**
* GitHub Login: @yzhong94
* Microsoft Alias: **yizhon**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #25370](https://github.com/MicrosoftDocs/azure-docs/issues/25370) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Dan-cws 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
