### ISSUE TITLE
Error in ReplaceItem

### ISSUE THREAD

**Issue by e-leoni** [MicrosoftDocs/azure-docs.it-it#403]
I have an error when I try to replace an item on CosmosDB
await this.container.ReplaceItemAsync<Family>(itemBody, itemBody.Id, new PartitionKey(itemBody.LastName));

"Errors":["PartitionKey extracted from document doesn't match the one specified in the header"]
---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 6367067e-e9ce-6c2a-dd5d-a9de54735e78
* Version Independent ID: 18564fed-2285-8cab-39a0-e3f1c2407c19
* Content: [Compilare un'app console .NET per gestire i dati in un account API SQL di Azure Cosmos DB](https://docs.microsoft.com/it-it/azure/cosmos-db/sql-api-get-started#feedback)
* Content Source: [articles/cosmos-db/sql-api-get-started.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cosmos-db/sql-api-get-started.md)
* Service: **cosmos-db**
* Sub-service: **cosmosdb-sql**
* GitHub Login: @kirankumarkolli
* Microsoft Alias: **kirankk**

**Comment by srvbpigh** [comment]
Hello, @e-leoni
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by e-leoni** [comment]
Dear @srvbpigh ,
I've solved the problem. In my cosmos db, the partition key is "**/azienda**" and in my web app I try to write a new item that has the attribute "**Azienda**".
So I think Cosmos Db is case sensitive and It returns that error.
Now It works.

Thank you very much for your support.
Best regards,
emanuele

**Comment by CeciAc** [comment]
Hello, @e-leoni 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
I see the issue was already solved. In the future, please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
