### ISSUE TITLE
Drive doesn't exist

### ISSUE THREAD

**Issue by gmlion** [MicrosoftDocs/azure-docs.it-it#419]
When using the "Mount the Azure file share with PowerShell" script, I had to add -Scope Global to the New-PsDrive command to keep the drive after script execution

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: c12f1ea9-6446-be01-22fe-885fb945d22c
* Version Independent ID: 634f8ace-1a8c-6811-627b-fdfbdd1942a3
* Content: [Usare una condivisione file di Azure con Windows](https://docs.microsoft.com/it-it/azure/storage/files/storage-how-to-use-files-windows#feedback)
* Content Source: [articles/storage/files/storage-how-to-use-files-windows.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/storage/files/storage-how-to-use-files-windows.md)
* Service: **storage**
* Sub-service: **files**
* GitHub Login: @roygara
* Microsoft Alias: **rogarana**

**Comment by srvbpigh** [comment]
Hello, @gmlion
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @gmlion, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/45061. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
