### ISSUE TITLE
AADSTS90092 GraphNonRetryableError

### ISSUE THREAD

**Issue by nickgsoft** [MicrosoftDocs/azure-docs.it-it#420]
I see there are error codes listed on the doc, but not all the Error codes have guide to resolve them. 
For an example 👍 i am getting error  "AADSTS90092: Non-retryable error has occurred." at the moment which i understood from the document that it is "AADSTS90092 | GraphNonRetryableError"

But there is no further guide from that. Any thing you can assist regarding this GraphNonRetryableError?

**Comment by srvbpigh** [comment]
Hello, @nickgsoft
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @nickgsoft, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46157. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by nickgsoft** [comment]
@srvbpigh , you are saying that you are migrating to #46157 and #46157 is saying they are migrating to #420. 
Is this really going to be handled or we gonna play catch 22. ?
