### ISSUE TITLE
Sql connector with onpremises gateway in Visual studio

### ISSUE THREAD

**Issue by DanieleG90** [MicrosoftDocs/azure-docs.it-it#421]
Where I can find the parameters for the on premises gateway in the LogicApp.json and LogicApp.parameters.json files in Visual Studio?
I saw server, database, username, password and  sqlConnectionString, is the last one for the on premises gateway? How?

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: 5e190390-dc83-246e-3e69-189f33d67ed7
* Version Independent ID: 66132130-9d94-fc33-7bc4-a54ee270efbc
* Content: [Connettersi a SQL Server o al database SQL di Azure](https://docs.microsoft.com/it-it/azure/connectors/connectors-create-api-sqlazure#connect-sql-server)
* Content Source: [articles/connectors/connectors-create-api-sqlazure.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/connectors/connectors-create-api-sqlazure.md)
* GitHub Login: @carolinacmoravia

**Comment by srvbpigh** [comment]
Hello, @DanieleG90
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @DanieleG90, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46905. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
