### ISSUE TITLE
Mention default unique constraint on id

### ISSUE THREAD

**Issue by matteopessina** [MicrosoftDocs/azure-docs.it-it#427]
I find out that there is a default unique constraint on the "id" property, within a partition, but I do not find a mention in the documentation. 

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: bf261de8-a6fa-9497-ffff-106550e2a537
* Version Independent ID: ee0468ba-1b3b-6ba4-d9f6-c60da3e7c486
* Content: [Usare chiavi univoche in Azure Cosmos DB](https://docs.microsoft.com/it-it/azure/cosmos-db/unique-keys#feedback)
* Content Source: [articles/cosmos-db/unique-keys.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cosmos-db/unique-keys.md)
* Service: **cosmos-db**
* GitHub Login: @markjbrown
* Microsoft Alias: **mjbrown**

**Comment by srvbpigh** [comment]
Hello, @matteopessina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @matteopessina 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue # https://github.com/MicrosoftDocs/azure-docs/issues/38378 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
