### ISSUE TITLE
Update tag list

### ISSUE THREAD

**Issue by vtontodonato-c** [MicrosoftDocs/azure-docs.it-it#435]
How to check the latest update tag list for "cognitive-services-speech-to-text" ... there are images that are not reported into this list.

---
#### Dettagli del documento

⚠ *Non modificare questa sezione. È necessaria per i collegamenti relativi ai problemi tra docs.microsoft.com ➟ GitHub.*

* ID: fca30c2b-eff8-66da-62ac-c080f67f140a
* Version Independent ID: 748a94e5-a289-5855-c3d8-0b8152254a99
* Content: [Tag delle immagini di contenitori in Servizi cognitivi - Azure Cognitive Services](https://docs.microsoft.com/it-it/azure/cognitive-services/containers/container-image-tags)
* Content Source: [articles/cognitive-services/containers/container-image-tags.md](https://github.com/MicrosoftDocs/azure-docs.it-it/blob/master/articles/cognitive-services/containers/container-image-tags.md)
* Service: **cognitive-services**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @vtontodonato-c
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54252](https://github.com/MicrosoftDocs/azure-docs/issues/54252) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @vtontodonato-c, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54252. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
